name: 🐛 Bug Report & Test Failures
description: Report unexpected behaviors or failing tests
title: "[BUG] "
labels: ["bug", "help wanted"]
body:
  - type: markdown
    attributes:
      value: "Please fill out this form with as much detail as possible to help us pinpoint the issue."
  - type: input
    attributes:
      label: Summary
      description: Provide a brief summary of the issue.
      placeholder: "e.g., Function fails to return the correct value."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: |
        1. Deploy the contract...
        2. Call the function...
        3. The incorrect value is returned...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected vs. Actual Behavior
      description: Detail the expected outcome versus what actually happened.
      placeholder: "Expected to return X, but got Y instead."
    validations:
      required: true
  - type: input
    attributes:
      label: Environment
      description: Specify your development environment (e.g., compiler version, test framework).
      placeholder: "Solidity v0.8.4, Hardhat v2.3.0"
  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
